# Site settings
baseurl: "" # Does this do anything?
permalink: /:title/
show_excerpts: true
timezone: Europe/London

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom add-on settings
paginate: 10
paginate_path: page/:num/

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# Theme-specific settings
minima:
  skin: dark # Temporary
  social_links:
  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Fork config
accent_colour: "#075e78"
giscus_repo: REPLACEME
giscus_repo_id: REPLACEME
giscus_category: Comments
giscus_category_id: REPLACEME
kofi_enabled: true
title: MinimaJake
description: This is the core minima fork used for Jake sites
url: "https://core.jakelee.co.uk" # Does this do anything?