# Basic site setup
title: minimaJake
description: An example of & updates from the minima fork minimaJake.
accent_colour: "#951A00"
theme_version: 1.0.10

# Optional native feature customisation (delete to turn off)
table_of_contents_header: "Jump to:"
table_of_contents_collapsible: true
post_end_promo: <i><b>Enjoyed this article? You'll like "<a href="https://jakeweeklee.substack.com">Jake Week Lee</a>", a weeklyish newsletter of articles & found media!</b></i>
google_analytics: G-HRJSZQJJ2G
replace_read_time_with_word_count: true
show_excerpts_html: true
open_external_links_in_new_tab: false

# Third party feature customisation (delete to turn off)
giscus_repo: JakeSteam/minimaJake
giscus_repo_id: R_kgDOI3xllA
giscus_category: Comments
giscus_category_id: DIC_kwDOI3xllM4CT62g
kofi_id: internethistory
kofi_button_text: Tip on Ko-fi
kofi_floating_text: Tip / Suggest

# Network site picker
network:
  - { name: Programming, url: "https://blog.jakelee.co.uk", colour: "#2a7ae2" }
  - { name: Internet History, url: "https://history.jakelee.co.uk", colour: "#075e78" }
  - { name: Theme, url: "https://minima.jakelee.co.uk", colour: "#951A00" }
  - { name: Cat Charity, url: "https://news.codecured.org", colour: "#111b6d" }
  - { name: Everything Else, url: "https://jakelee.co.uk", colour: "#acacac" }

# Social / dark mode settings
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/JakeSteam" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/Jake-Lee" }
    - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/608312/Jake-Lee" }
    - { platform: twitter, user_url: "https://www.twitter.com/JakeLeeUK" }
    - { platform: email, user_url: "mailto:minima@jakelee.co.uk", user_title: "minima@jakelee.co.uk" }
    - { platform: code, user_url: "https://github.com/JakeSteam/minimaJake", user_title: "JakeSteam/minimaJake" }
    - { platform: rss, user_url: "/feed.xml", user_title: "RSS Feed" }
    - { platform: substack, user_url: "https://jakeweeklee.substack.com/", user_title: "Jake Week Lee" }
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

###
# Below here probably doesn't need changing #
###

# Site settings
permalink: /:title/
timezone: Europe/London

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination settings
paginate: 10
paginate_path: page/:num/

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true